title: Info Berita Kalbar # Judul situs web Anda
description: Website Artikel Terkini 2025 # Deskripsi situs web Anda
author: Kalbar Info # Nama Anda
email: anymone69@gmail.com # Alamat email Anda
baseurl: "" # Subdirektori tempat situs web Anda di-host (biasanya kosong untuk GitHub Pages)
url: "https://infoberita-kalbar.github.io/news/" # URL lengkap situs web Anda


# Plugin
plugins:
  - jekyll-sitemap # Contoh plugin: jekyll-sitemap
